name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: 
  push:
    branches: [ "github-actions" ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "Your branch is ${{ github.ref }} and Your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls -alF ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
